<div id="school_LForm" style="display:none">
    <form id="test-form" class="white-popup-block mfp-hide">
        <div class="popup_box">
            <h3>Log In</h3>
            <form action="#">
                <div class="row">
                    <div class="col-xl-12 col-md-12">
                        <input type="email" placeholder="Enter email">
                    </div>
                    <div class="col-xl-12 col-md-12">
                        <input type="password" placeholder="Password">
                    </div>
                    <div class="col-xl-12">
                        <button type="submit" class="boxed_btn_orange">Sign in</button>
                    </div>
                    <p class="doen_have_acc">Don’t have an account? <a class="dont-hav-acc" href="#test-form2">Sign Up</a></p>
                </div>
            </form>
        </div>
    </form>
</div>

<div id="school_SForm" style="display: none">
    <form id="test-form2" class="white-popup-block mfp-hide">
        <div class="popup_box">
            <h3>Registration</h3>
            <form action="#">
                <div class="row">
                    <div class="col-xl-12 col-md-12">
                        <input type="email" placeholder="Enter email">
                    </div>
                    <div class="col-xl-12 col-md-12">
                        <input type="password" placeholder="Password">
                    </div>
                    <div class="col-xl-12 col-md-12">
                        <input type="Password" placeholder="Confirm password">
                    </div>
                    <div class="col-xl-12">
                        <button type="submit" class="boxed_btn_orange">Sign Up</button>
                    </div>
                    <p class="doen_have_acc">Already have an account? <a class="dont-hav-acc" href="#test-form">Sign Up</a></p>
                </div>
            </form>
        </div>
    </form>
</div>